name: Nightly Script Run

on:
  schedule:
    - cron: '0 7 * * *'  # This means every day at 2 AM Central Time (CDT, UTC-5)
  workflow_dispatch:  # This allows you to manually trigger the workflow from the GitHub UI

jobs:
  run_script:
    runs-on: ubuntu-latest  # Using the latest version of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository to the GitHub runner

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your dependencies

    - name: Run the Python script
      run: |
        python your_script.py  # Replace with the actual filename of your script

    - name: Commit and push generated files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Nightly update: generated new map"
        git push origin main  # Push changes to the repository if necessary
